""" Written by Joseph Surrey 05/05/2023
"""

NUMBERS = [["What is the Māori word for one?", "tahi"],
           ["What is the English word for tahi?", "one"],
           ["What is the Māori word for two?", "rua"],
           ["What is the English word for rua?", "two"],
           ["What is the Māori word for three?", "toru"],
           ["What is the English word for toru?", "three"],
           ["What is the Māori word for four?", "whā"],
           ["What is the English word for whā?", "four"],
           ["What is the Māori word for five?", "rima"],
           ["What is the English word for rima?", "five"],
           ["What is the Māori word for six?", "ono"],
           ["What is the English word for ono?", "six"],
           ["What is the Māori word for seven?", "whitu"],
           ["What is the English word for whitu?", "seven"],
           ["What is the Māori word for eight?", "waru"],
           ["What is the English word for waru?", "eight"],
           ["What is the Māori word for nine?", "iwa"],
           ["What is the English word for iwa?", "nine"],
           ["What is the Māori word for ten?", "tekau"],
           ["What is the English word for tekau?", "ten"]]
MAORI_MONTHS = [["What is the Māori word for January?", "Kohitātea"],
                ["What is the English word for January?", "January"],
                ["What is the Māori word for February?", "Hui-tanguru"],
                ["What is the English word for February?", "February"],
                ["What is the Māori word for March?", "Poutū-te-rangi"],
                ["What is the English word for March?", "March"],
                ["What is the Māori word for April?", "Paenga-whāwhā"],
                ["What is the English word for April?", "April"],
                ["What is the Māori word for May?", "Haratua"],
                ["What is the English word for May?", "May"],
                ["What is the Māori word for June?", "Pipiri"],
                ["What is the English word for June?", "June"],
                ["What is the Māori word for July?", "Hōngongoi"],
                ["What is the English word for July?", "July"],
                ["What is the Māori word for August?", "Here-turi-kōkā"],
                ["What is the English word for August?", "August"],
                ["What is the Māori word for September?", "Mahuru"],
                ["What is the English word for September?", "September"],
                ["What is the Māori word for October?", "Whiringa-ā-nuku"],
                ["What is the English word for October?", "October"],
                ["What is the Māori word for November?", "Whiringa-ā-rangi"],
                ["What is the English word for November?", "November"],
                ["What is the Māori word for December?", "Hakihea"],
                ["What is the English word for December?", "December"]]
MAORI_DAYS = [["What is the Māori word for Monday?", "Rāhina"],
              ["What is the English word for Rāhina?", "Monday"],
              ["What is the Māori word for Tuesday?", "Rātū"],
              ["What is the English word for Rātū?", "Tuesday"],
              ["What is the Māori word for Wednesday?", "Rāapa"],
              ["What is the English word for Rāapa?", "Wednesday"],
              ["What is the Māori word for Thursday?", "Rāpare"],
              ["What is the English word for Rāpare?", "Thursday"],
              ["What is the Māori word for Friday?", "Rāmere"],
              ["What is the English word for Rāmere?", "Friday"],
              ["What is the Māori word for Saturday?", "Rāhoroi"],
              ["What is the English word for Rāhoroi?", "Saturday"],
              ["What is the Māori word for Sunday?", "Rātapu"],
              ["What is the English word for Rātapu?", "Sunday"]]
